### ISSUE TITLE
server responded with status of error 404 not. found

### ISSUE THREAD

**Issue by gokigoks** [OttoRobba/browserify-phaser#1]
I got this error from from google chrome console when i tried beefing. its pointing at bundle.js 
  "Failed to load resource: the server responded with a status of 404 (Not Found)"

I didn't change anything in the code, btw.
what can i do?

**Comment by ThaisRobba** [comment]
Can you check what file is said to be missing?

**Comment by gokigoks** [comment]
It works now but I didnt change anything. Just tried again for a few minutes. My bet would be the failure in loading files was'nt local? I'll try to resimulate the problem. thanks!
